allowBuilds:
  '@fortawesome/fontawesome-common-types': true
  '@fortawesome/free-solid-svg-icons': true
  '@parcel/watcher': true
  core-js: true
  unrs-resolver: true

overrides:
  "@codemirror/state": "6.7.1"
  "@embroider/util": "1.13.5"
  "caniuse-lite": "1.0.30001809"
  "ember-auto-import": "$ember-auto-import"
  "ember-headless-form>tracked-built-ins": "$tracked-built-ins"
  "ember-math-helpers": "$ember-math-helpers"
  "ember-truth-helpers": "$ember-truth-helpers"
  "tracked-toolbox": "$tracked-toolbox"
  "@ember/render-modifiers": "$@ember/render-modifiers"
  "@ember/test-waiters": "^3.1.0"

patchedDependencies:
  "ember-source@5.12.0": "patches/ember-source@5.12.0.patch"
