when:
  - event: push
    branch: futurenow

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO}
      tags: futurenow
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
