when:
  - event: push
    branch: master

steps:
  push-latest:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO}
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

