when:
  - event: pull_request

steps:
  install:
    image: danlynn/ember-cli:5.12.0-node_20.18
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  lint-js:
    image: danlynn/ember-cli:5.12.0-node_20.18
    group: lint
    commands:
      - corepack enable
      - pnpm lint:js
  lint-hbs:
    image: danlynn/ember-cli:5.12.0-node_20.18
    group: lint
    commands:
      - corepack enable
      - pnpm lint:hbs
  lint-types:
    image: danlynn/ember-cli:5.12.0-node_20.18
    group: lint
    commands:
      - corepack enable
      - pnpm lint:types
  dependency-lint:
    image: danlynn/ember-cli:5.12.0-node_20.18
    group: lint
    commands:
      - corepack enable
      - pnpm lint:deps
  test:
    image: danlynn/ember-cli:5.12.0-node_20.18
    commands:
      - corepack enable
      - pnpm test:ember

