when:
  - event: pull_request

steps:
  install:
    image: danlynn/ember-cli:5.12.0-node_20.18
    commands:
      - npm ci
  lint-js:
    image: danlynn/ember-cli:5.12.0-node_20.18
    group: lint
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:5.12.0-node_20.18
    group: lint
    commands:
      - npm run lint:hbs
  lint-types:
    image: danlynn/ember-cli:5.12.0-node_20.18
    group: lint
    commands:
      - npm run lint:types
  dependency-lint:
    image: danlynn/ember-cli:5.12.0-node_20.18
    group: lint
    commands:
      - npm run lint:deps
  test:
    image: danlynn/ember-cli:5.12.0-node_20.18
    commands:
      - npm run test:ember

